[package]
name = "pallet-evmless-precompile-fungibles"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "Fungible precompile for EVMless pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
num_enum = { version = "0.5.4", default-features = false }

# Substrate
frame-system = { workspace = true }
frame-support = { workspace = true }
sp-std = { workspace = true }
sp-core = { workspace = true }
pallet-assets = { workspace = true }


# Frontier
fp-evm = { workspace = true }
pallet-evmless = { workspace = true }

# Precompile Utils
precompile-utils = { workspace = true }

[dev-dependencies]
scale-codec = { package = "parity-scale-codec", workspace = true }
scale-info = { workspace = true }
# Substrate
frame-system = { workspace = true }
pallet-balances = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true }
pallet-utility = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"num_enum/std",
	# Substrate
	"frame-support/std",
	"sp-std/std",
	"sp-core/std",
	# Frontier
	"fp-evm/std",
	"pallet-evmless/std",
	"pallet-assets/std"
]
