[package]
authors = {workspace = true}
description = "Allows to populate the pallet-evm state from a legacy chain"
edition = {workspace = true}
name = "pallet-evm-migration"
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex-literal = "0.3.4"
scale-codec = { package = "parity-scale-codec", workspace = true }

frame-benchmarking = {workspace = true, optional = true}
frame-support = {workspace = true}
frame-system = {workspace = true}
hex = {workspace = true}
log = {workspace = true}
scale-info = {workspace = true}
sp-core = {workspace = true}
sp-runtime = {workspace = true}
sp-std = {workspace = true}
sp-io = {workspace = true, optional = true}
pallet-balances = {workspace = true}
pallet-evm = {workspace = true}

[dev-dependencies]
pallet-balances = {workspace = true}
pallet-ethereum = {workspace = true}
pallet-timestamp = {workspace = true}


[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks", "hex/alloc", "sp-io"]
std = [
  "scale-codec/std",
  "frame-benchmarking?/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "sp-core/std",
  "sp-std/std",
  "pallet-evm/std",
  "pallet-balances/std",
  "pallet-ethereum/std",
]
try-runtime = ["frame-support/try-runtime"]
