name: Docs

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: make setup

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website
        run: |
          cd docs
          yarn install
          yarn run build

      - name: Build rustdocs
        run: cargo doc --all --no-deps

      - name: Copy rustdocs
        run: cp -r ./target/doc docs/.vuepress/dist/rustdocs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./docs/.vuepress/dist
          keep_files: true
