name: Rust

on:
  push:
    branches:
      - master
      - 'polkadot-v**'
  pull_request:
    branches:
      - master
      - 'polkadot-v**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Cache Dependencies & Build Outputs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-unittest-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-unittest-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-unittest-
            ${{ runner.os }}-cargo-

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Install Rust Toolchain
        run: make setup

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Unit Tests
        run: make test-release

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Cache Dependencies & Build Outputs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-integration-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-integration-test-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-integration-test-
            ${{ runner.os }}-cargo-

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Install Rust Toolchain
        run: make setup

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Client
        run: make build-release

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Integration Tests
        run: make integration-test
